= A reflection helper for go
Greg Hall, greghall@bantling.me

Simplify usage of reflection, to make it less tedious and technical:

* Match types
** Provide an instance of the type, a reflect.Value, or reflect.Type
** Match a single type or one of multiple choices
** Indicate the minimum and maximum number of pointer indirections
** Provide a value that is a pointer, but specify no indirections (or vice-versa)
** Matches against a reflect.Type
* Match function signatures
** Builds on matching types, but allows them to be optional
** Return indexes indicating which parameters and return types matched and a bool, for use cases with optional parameters and/or return types
** Any parameter or return type position can be optional, not just at the end
** Return just a bool to indicate whether or not a function matches
** Fluent api
* Examine references
** Deref a reflect.Value or reflect.Type to get to the on-pointer value/type pointed to
** Fully deref all parts of a reflect.Type (eg *[]**[]***int becomes [][]int)
** Get the number of indirections in a type (eg ***int = 3)
** Create any numberof indiretions to a value (eg given an int, create a **int that points to it)
* Visit a value
** Any kind of value except for Invalid, Uintptr and UnsafePointer
** Only implement the methods your visiter needs, ignoring the rest
** ValueVisitorAdapter adapts an implementation of a subset of visiter methods into an implementation of all of them
** ValuePrinter prints out values by fully dereferencing them, printing addresses if desired
** ValuePrinter is really useful for debug logging types like slices of pointers
** ValueDepthFirstWalker walks a value, executing methods of a visiter

== Examples

[source, Go]
----
type Foo struct{}
type Bar struct{}

// Match a func that accepts a required int and an optional struct of any type
matcher := NewFuncMatcher().
  WithParamType(0).
  WithOptionalParamType(reflect.Struct)

// Returns true
matcher.Matches(func(int) {})
matcher.Matches(func(int, Foo) {})
matcher.Matches(func(int, Bar) {})

// Returns false
matcher.Matches(func(Foo) {}))

// Returns []int{0}, []int{}, true
matcher.MatchingIndexes(func(int) {})

// Returns []int{0, 1}, []int{}, true
matcher.MatchingIndexes(func(int, Foo) {})

// Returns nil, nil, false
matcher.MatchingIndexes(func(Foo) {}))

// Returns "func(int, [struct])"
matcher.String()

// Match a func that accepts Foo or *Foo and returns *Bar
matcher = NewFuncMatcher().
  WithParamType(Foo{}, goreflect.Value, goreflect.Ptr). // Minimum pointer indirection = value, maximum = pointer
  WithReturnType(Bar{}, goreflect.Ptr) // Minimum pointer indirection = maximum = pointer

// Returns true
matcher.matches(func(Foo) *Bar {return (*Bar)(nil)})
matcher.matches(func(*Foo) *Bar {return (*Bar)(nil)})

// Returns false
matcher.matches(func(**Foo) *Bar {return (*Bar)(nil)})
matcher.matches(func(Foo) Bar {return Bar{}})
matcher.matches(func(Foo) **Bar {return (**Bar)(nil)})

// Returns []int{0}, int[]{0}, true
matcher.MatchingIndexes(func(Foo) *Bar {return (*Bar)(nil)})
matcher.MatchingIndexes(func(*Foo) *Bar {return (*Bar)(nil)})

// Returns nil, nil, false
matcher.MatchingIndexes(func(**Foo) *Bar {return (*Bar)(nil)})
matcher.MatchingIndexes(func(Foo) Bar {return Bar{}})
matcher.MatchingIndexes(func(Foo) **Bar {return (**Bar)(nil)})

// Returns "func([*]Foo, *Bar)"
matcher.String()

// Match a func that accepts a required int or string and returns a required int or string.
matcher = NewFuncMatcher().
  WithParamTypes(goreflect.Value, goreflect.Value, 0, "").
  WithReturnTypes(goreflect.Value, goreflect.Value, "", 0)

// Returns true
matcher.matches(func(int) int {return 0})
matcher.matches(func(string) int {return 0})
matcher.matches(func(int) string {return ""})
matcher.matches(func(string) string {return ""})

// Returns false
matcher.matches(func() {})
matcher.matches(func(int) {})
matcher.matches(func() string {})

// Returns "func(int|string) int|string"
matcher.String()

// Print out a structure with pointers
var (
  i      = 5
  ptr    = &i
  ptrptr = &ptr
  p      = &ValuePrinter{}
  w      = NewValueDepthFirstWalker(NewValueVisitorAdapter(p))
  pp     = &ValuePrinter{WithAddress: true}
  wp     = NewValueDepthFirstWalker(NewValueVisitorAdapter(pp))
)

// Returns "5"
w.walk(i)
p.Result()

// Returns "5"
wp.walk(i)
pp.Result()

// Returns "&5"
w.walk(ptr)
p.Result()

// Returns "&@[0x...]5"
wp.walk(ptr)
pp.Result()

// Returns "&&5"
w.walk(ptrptr)
p.Result()

// Returns "&@[0x...]&@[0x...]5"
wp.walk(ptrptr)
pp.Result()
----
